@renewToken= dn4XiQQd98ejiOJNgZxse7snsB7hOnBVb8LhqQ-ba-zp6qWUd8eTiODqmGAP_3z61BTCvZfzFSOuu0WhCimC5qCsGEv-r8VzHozzr0zIDAo74kELNyX0OuMtcR_W0DkNoQCJlAkw57EJUI1RMY-CxWv7AJsXZxyEc3VoCbvzZN-RI4k3djil_604B2_fGHbldGPzWSzm
@accessToken= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMTExMTEiLCJ1c2VybmFtZSI6Ik1HLzExeHgiLCJleHAiOjE3ODc1NzA3NTJ9.kYcEtLt-tBNgYW1ShTy1g6W_4XssBv_r7393R-HOUss

### Current User 
# @name current user
POST {{EXPO_PUBLIC_API_URL}}/current-user/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json


### Registration Status
# @name registrationStatus
POST {{EXPO_PUBLIC_API_URL}}/get_registration_status/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "ppo_no": "gAAAAABqiAB7ULfPNzlIlH9R3fWxJexz9ykiQPjUg3I8gQNKoOP8N0W1RNGzojON0jnSEcue10dU0BPrwkakfzQN80WNm_GkMQ==",
  "version":"24"
}


### Create Pensioner
# @name createPensioner
POST {{EXPO_PUBLIC_API_URL}}/api/create_pensioner/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "ppo_no": {{PPO_NO}},
  "dob": "",
  "bank_account_number": "",
  "password": ""
}

### Login
# @name login
POST {{EXPO_PUBLIC_API_URL}}/login/
Content-Type: application/x-www-form-urlencoded
Accept: application/json

# password=gAAAAABqiC_DHmRi4drx2JHBaoRC5QqLkdQ4-DVOwrpBO9zyubuE3pk0tqXcUvuKD6jRmO4YGGS3RwdSbMYAc3IDerk2KTwAU_yccs71k-DeYyKOEJsbLYbMOEPT-WT1pjvNy5R8qqT7HNZ9MNlOwKDeeaE6PcTXmwqM5qAmXh7ihoOFIN0J0g_GDAXPS635ISc8GFgfr0Z9LW6xzvMKGX0WVti3GUqvUAVkvq0kvQYEiBiP2FVOfr4SVDTh4Vu1HReekZ_X3DEgT6QdzelZ8OQpoecxpal9AVAqNYOJIxq9fGrP1OuYXk2a-ZpYkVqfaCGd1gpQ86yb&username=gAAAAABqiC_DFjgr6n0qB4SDp-OkauwgnIdWaMSr1oU1cUQUsvmLMq6DCWdAMFSmtdSCoxA3XU2jqQj8Asq0_uTijnUJAHpeZQ%3D%3D&version=24
password=gAAAAABqidLuAv3Y11Y-XURux_JJ2QbKdcdQSUMu9wA4QUwcHSiGIdHrzv2f-dxnr_G-DNP0G0xc08PBpZnmuw_xM5F5BO21lVDpA8R4s0gloY_wNVH9WzSp5VT3S_IqUc1MNfCJ3cBKfVJcuFdwveo75qlJ7lHaeLSNGInAzRkz5er8VzWwM4dOux4qR85i3lDoU6qvqjTmLTsdN9N0ztUKu4lM6wHXElf-EHbj7o6TjrKAQpolAjDESczzkmFiVlxC8wtb6UboSvMvACiRb4K13FleTIZiNjKrjqeKGaoONWO9H7xYN8-irup-DPo_iCsAKOZXriWm&username=gAAAAABqidLuYDWOen2IiDeDxVlamXiBg30bFkIDyQKNLGw-RBOmxV_Inx4txJU_E-tJKUoOasIYZwmwVIAXAA1xSEkm39jrrw%3D%3D&version=24
# password=gAAAAABqidnL2ughyi8PHFSvWOVI-XVDB6w-BojCjHTrXTuk6qc-ralAvF9Hmk3MEw4B0GcueYmvVfUX5uYGiM9goGijie95nwNuLXDWid8ejd0-KXXhseCcCVlTLOs5fP2DrD_snES1kMsP-NRQgxx0RxtxOFgidegbYzLy244q7xEEeCzJWG7z1K_zsNBRimbnLcS0_8mBwc_xAzsW6RzuPIR2tlyTyg6R9T__5zMTXUSLVqwDMUpQpgLX5kr2q0W6ZPXOBlQO3FOhkDBDYa9CjMqcOaZ7Niwmy1X3PlY2JaObSOqBo2DYkh7KuPWgMrxCo7-uD80D&username=gAAAAABqidnLzEsa4btJleB2b-sqMLMbCXzCQhBRD1FpAo5XrYNF7izQI0jSb6KJtAyepW-p4686aJrwo6oD4BFD0Ua6e0KBwA%3D%3D&version=24

### Logout
# @name login
POST {{EXPO_PUBLIC_API_URL}}/logout/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 

}

### Verification
# @name verification
POST {{EXPO_PUBLIC_API_URL}}/api/verification/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json


### DLC
# @name dlc
POST {{EXPO_PUBLIC_API_URL}}/api/lc/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "selfVerNec": "",
  "selfVerNmc": "",
  "device": "",
  "device_id": "",
  "ver_mode_code": "",
  "self_ver_code": "",
  "place": ""
}


### Verification Status
# @name verificationStatus
POST {{EXPO_PUBLIC_API_URL}}/api/verification_status/
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "ppo_no": "gAAAAABqiAB7ULfPNzlIlH9R3fWxJexz9ykiQPjUg3I8gQNKoOP8N0W1RNGzojON0jnSEcue10dU0BPrwkakfzQN80WNm_GkMQ==",
}

# Response
# {
#   "is_valid": "01",
#   "ver_date": "25-04-2026",
#   "ver_nec": "No",
#   "ver_nmc": "No",
#   "ver_place": "",
#   "ver_status": "Photo is Approved. Do your next Face Verification on or after 25-10-2026\n\n The link to our Privacy Policy can be found on the manual of this app.",
#   "ver_time": "16:16:31"
# }

### Change Password
# @name changePassword
POST {{EXPO_PUBLIC_API_URL}}/api/change_password/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "oldPassword":"",
  "newPassword":"",
}

#
### Validate Token
# @name validateToken
POST {{EXPO_PUBLIC_API_URL}}/api/validate_token/
Content-Type: application/x-www-form-urlencoded
Authorization: accessToken {{accessToken}}
Accept: application/json

uid=NzMwMDAwMTAzNA%3D%3D&request_token={{renewToken}}


### Manual
# @name manual
GET {{EXPO_PUBLIC_API_URL}}/manual.html/
Authorization: accessToken {{accessToken}}

### Encryption
# @name encryption
POST http://localhost:3000/api/cssp/encrypt
Authorization: accessToken {{accessToken}}

{ 
  "username":"{{USERNAME}}",
  "password":"YTg1YzRmYzI2OTcxZDdhMTgxMTg0YzFhYzc5NDU3NTA2M2MyZDVjNDAyN2RiNGEzMmNlZjQ4YmE2YjE0Njg1YjA2eTExeDI4ejM4eDUzZHU2Ynk0MTh4MzUybTQwNXU1OTR1MTFheTQ3NXkyOTN5NDZtNDQwbTQzNG0yMWZ4MzRmdTI4N3UyNTB4"
}

### Decryption
# @name decryption
POST http://localhost:3000/api/cssp/decrypt
Authorization: accessToken {{accessToken}}

{
  "password": "1fbd4e08c1f6802e0aca322147c4026fbea5a93fa7fee777c306ab220a3c3a32",
  "version":"24"
}

### Decryption
# @name decryption
POST http://localhost:3000/api/cssp/format-password
Authorization: accessToken {{accessToken}}

{
  "password": "{{PASSWORD}}",
}
