@renewToken= OpGcCOKoqydVGvFht3rs6ks269kBAgpLvP1rDiVETQ4twL03SAT4qFwnj8vDWf8clPKEn6bJ997CuJ4-p05rUc--JMhFR493FyTgmgwpIAvXSGbOs6yXPr2jeQsQvCpvedAiACRPr-iJ6wPkRu-TZBSXVO1mid-bf5dhYnIS7EQA97NM9VrQOwf-KqpmtofstQZeZ7Z9
@accessToken= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNzMwMDAwMTAzNCIsInVzZXJuYW1lIjoiTUcvU0YvMTU2NzMiLCJleHAiOjE3ODczNTAyNDN9.ZW5JhvMZoVPNbKkczj4FsaYdGg_fLT_PPj862BEvBrA
# {
#   "approval": "00",
#   "has_dlc": "00",
#   "name": "RIBENA JAMU",
#   "renew_token": "_dDVpsErVXXI1qNIrUaUCBoF--k2JOzVRPRpJ3ejWpp5fQ01lu5d70sQaZzwPaDTi337gK7IIIxPdw3fFdB_9XTezYSdqz7E9tJzGey2_XZ417miJWzd73SulyrQ6GR98nBVGEw_zx0YnMUrPTfYmYHZ5mlDsPP4Z7bfb30QlA2yrhW-XKowYRmNIWG6Yr8LpeFfmiAN",
#   "uid": "NzMwMDAwMTAzNA==",
#   "username": "TUcvU0YvMTU2NzM="
# }

### Current User 
# @name current user
POST {{EXPO_PUBLIC_API_URL}}/current-user/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json


### Registration Status
# @name registrationStatus
POST {{EXPO_PUBLIC_API_URL}}/get_registration_status/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "ppo_no": "gAAAAABqiAB7ULfPNzlIlH9R3fWxJexz9ykiQPjUg3I8gQNKoOP8N0W1RNGzojON0jnSEcue10dU0BPrwkakfzQN80WNm_GkMQ==",
  "version":"24"
}


### Create Pensioner
# @name createPensioner
POST {{EXPO_PUBLIC_API_URL}}/api/create_pensioner/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "ppo_no": {{PPO_NO}},
  "dob": "",
  "bank_account_number": "",
  "password": ""
}

### Login
# @name login
POST {{EXPO_PUBLIC_API_URL}}/login/
Content-Type: application/x-www-form-urlencoded
Accept: application/json

password=gAAAAABqiC_DHmRi4drx2JHBaoRC5QqLkdQ4-DVOwrpBO9zyubuE3pk0tqXcUvuKD6jRmO4YGGS3RwdSbMYAc3IDerk2KTwAU_yccs71k-DeYyKOEJsbLYbMOEPT-WT1pjvNy5R8qqT7HNZ9MNlOwKDeeaE6PcTXmwqM5qAmXh7ihoOFIN0J0g_GDAXPS635ISc8GFgfr0Z9LW6xzvMKGX0WVti3GUqvUAVkvq0kvQYEiBiP2FVOfr4SVDTh4Vu1HReekZ_X3DEgT6QdzelZ8OQpoecxpal9AVAqNYOJIxq9fGrP1OuYXk2a-ZpYkVqfaCGd1gpQ86yb&username=gAAAAABqiC_DFjgr6n0qB4SDp-OkauwgnIdWaMSr1oU1cUQUsvmLMq6DCWdAMFSmtdSCoxA3XU2jqQj8Asq0_uTijnUJAHpeZQ%3D%3D&version=24


### Logout
# @name login
POST {{EXPO_PUBLIC_API_URL}}/logout
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 

}

### Verification
# @name verification
POST {{EXPO_PUBLIC_API_URL}}/api/verification/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json


### DLC
# @name dlc
POST {{EXPO_PUBLIC_API_URL}}/api/lc/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "selfVerNec": "",
  "selfVerNmc": "",
  "device": "",
  "device_id": "",
  "ver_mode_code": "",
  "self_ver_code": "",
  "place": ""
}


### Verification Status
# @name verificationStatus
POST {{EXPO_PUBLIC_API_URL}}/api/verification_status/
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "ppo_no": "gAAAAABqiAB7ULfPNzlIlH9R3fWxJexz9ykiQPjUg3I8gQNKoOP8N0W1RNGzojON0jnSEcue10dU0BPrwkakfzQN80WNm_GkMQ==",
}

# Response
# {
#   "is_valid": "01",
#   "ver_date": "25-04-2026",
#   "ver_nec": "No",
#   "ver_nmc": "No",
#   "ver_place": "",
#   "ver_status": "Photo is Approved. Do your next Face Verification on or after 25-10-2026\n\n The link to our Privacy Policy can be found on the manual of this app.",
#   "ver_time": "16:16:31"
# }

### Change Password
# @name changePassword
POST {{EXPO_PUBLIC_API_URL}}/api/change_password/
Content-Type: application/json
Authorization: accessToken {{accessToken}}
Accept: application/json

{ 
  "oldPassword":"",
  "newPassword":"",
}

#
### Validate Token
# @name validateToken
POST {{EXPO_PUBLIC_API_URL}}/api/validate_token/
Content-Type: application/x-www-form-urlencoded
Authorization: renewToken {{renewToken}}
Accept: application/json

uid=NzMwMDAwMTAzNA%3D%3D&request_token={{renewToken}}


### Manual
# @name manual
GET {{EXPO_PUBLIC_API_URL}}/manual.html/
Authorization: accessToken {{accessToken}}

### Encryption
# @name encryption
POST http://localhost:3000/api/cssp/encrypt
Authorization: accessToken {{accessToken}}

{ 
  "username":"{{USERNAME}}",
  "password":"MjAwZDVmYjI2YjdhZGNmMTYxMWM0ZjBhYzA5NDczNTA2M2YyYjU2NDU4MDQwNGE1Y2NlZjRkYmE2YjE0NmQ1YjA2dTExejI4eTM4ejM4Y3oxNjh2MTk4bTEzN3k0Mjd6MTUxeDEzM3Y0ODJ4MTRhbTk5eDIyMXkzOGZ6NDZ6NDc1djYxOHozNmRt"
}

### Decryption
# @name decryption
POST http://localhost:3000/api/cssp/decrypt
Authorization: accessToken {{accessToken}}

{
  "password": "gAAAAABqiAB7I3x8tidB3ykZGx_qIxHS6p6LZs4bMJnaba9GfrBef_EABQb6VyKnC2UWEP4Ie2bEDfe6XoQ0pnzzehBGO5W4xA==",
  "username": "gAAAAABqiAB7ULfPNzlIlH9R3fWxJexz9ykiQPjUg3I8gQNKoOP8N0W1RNGzojON0jnSEcue10dU0BPrwkakfzQN80WNm_GkMQ==",
  "version":"24"
}

### Decryption
# @name decryption
POST http://localhost:3000/api/cssp/format-password
Authorization: accessToken {{accessToken}}

{
  "password": "{{PASSWORD}}",
}
