# --------------------------------------------
# Pensioner v2
# --------------------------------------------

###  login
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "payload":"{{LOGIN_PAYLOAD}}"
}

###  pension statement
POST {{BASE_URL}}/paymentslip

{
  "payload":"{{DAT_PENSION_PAYMENT_SLIP_PAYLOAD}}"
}


### pension logout
POST {{BASE_URL}}/logout

{
 "token":"{{ACCESS_TOKEN}}"
}

### get ppo status 
POST {{BASE_URL}}/get_ppo_status
Content-Type: application/json

# //"payload": {"ppo_no": ""}

{
 "payload":"{{PPO_NO_ENCRYPTED}}"
}

### get facial registration
POST {{BASE_URL}}/get_ppo_status
Content-Type: application/json

# //{"ppo_no": ""}

{
 "payload":"{{REGISTRATION_PAYLOAD_V2}}"
}
